name: inspection_manager_app
description: سامانه مدیریت بازرسی
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  record: ^6.0.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  open_filex: ^4.7.0

  # خروجی Excel
  excel: ^4.0.6

  # خروجی Word
  docx_dart: ^1.2.0

  # پخش ویدئوی ورود
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/login_animation.mp4
